name: nlp_basics
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - aiodns=3.5.0=py312haa95532_1
  - aiohappyeyeballs=2.6.1=py312haa95532_0
  - aiohttp=3.13.2=py312h02ab6af_0
  - aiosignal=1.4.0=py312haa95532_0
  - altair=5.5.0=pyhd8ed1ab_1
  - annotated-types=0.6.0=py312haa95532_1
  - anyio=4.10.0=py312haa95532_0
  - aom=3.6.0=hd77b12b_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h02ab6af_0
  - arrow-cpp=21.0.0=h0399227_0
  - asttokens=3.0.0=py312haa95532_0
  - async-lru=2.0.5=py312haa95532_0
  - attrs=25.4.0=py312haa95532_2
  - aws-c-auth=0.9.0=h02ab6af_2
  - aws-c-cal=0.9.2=h02ab6af_1
  - aws-c-common=0.12.4=h02ab6af_0
  - aws-c-compression=0.3.1=h02ab6af_2
  - aws-c-event-stream=0.5.6=h02ab6af_0
  - aws-c-http=0.10.4=h02ab6af_0
  - aws-c-io=0.21.4=h02ab6af_0
  - aws-c-mqtt=0.13.3=h02ab6af_0
  - aws-c-s3=0.8.7=h02ab6af_0
  - aws-c-sdkutils=0.2.4=h02ab6af_1
  - aws-checksums=0.2.7=h02ab6af_1
  - aws-crt-cpp=0.34.0=h885b0b7_0
  - aws-sdk-cpp=1.11.638=hf0af688_0
  - babel=2.16.0=py312haa95532_0
  - beautifulsoup4=4.13.5=py312haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312haa95532_0
  - blinker=1.9.0=pyhff2d567_0
  - bottleneck=1.4.2=py312h540bb41_1
  - brotlicffi=1.0.9.2=py312h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.11.4=haa95532_0
  - cachetools=6.2.1=pyhd8ed1ab_0
  - cairo=1.18.4=he9e932c_0
  - catalogue=2.0.10=py312haa95532_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=2.0.0=py312h02ab6af_1
  - charset-normalizer=3.4.4=py312haa95532_0
  - click=8.2.1=py312haa95532_0
  - cloudpathlib=0.16.0=py312haa95532_1
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - confection=0.1.5=py312hbc747e5_0
  - contourpy=1.3.1=py312h214f63a_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cymem=2.0.11=py312h885b0b7_0
  - cython-blis=0.7.11=py312he558020_0
  - datasets=3.3.2=py312haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - debugpy=1.8.16=py312h885b0b7_1
  - decorator=5.2.1=py312haa95532_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.3.8=py312haa95532_0
  - et_xmlfile=2.0.0=py312haa95532_0
  - executing=2.2.1=py312haa95532_0
  - expat=2.7.3=h9214b88_0
  - filelock=3.20.0=py312haa95532_0
  - fontconfig=2.15.0=hd211d86_0
  - fonttools=4.60.1=py312h02ab6af_0
  - freeglut=3.4.0=h8a1e904_1
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.8.0=py312h885b0b7_0
  - fsspec=2024.12.0=py312haa95532_0
  - gflags=2.2.2=hd77b12b_1
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.45=pyhff2d567_0
  - glog=0.5.0=hd77b12b_1
  - gmp=6.3.0=h537511b_0
  - gmpy2=2.2.1=py312h827c3e9_0
  - graphite2=1.3.14=hd77b12b_1
  - h11=0.16.0=py312haa95532_1
  - harfbuzz=10.2.0=he2f9f60_1
  - hf-xet=1.1.8=py312h79d111c_0
  - httpcore=1.0.9=py312haa95532_0
  - httpx=0.28.1=py312haa95532_1
  - huggingface_hub=0.34.4=py312haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.11=py312haa95532_0
  - importlib-metadata=8.5.0=py312haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.30.1=py312haa95532_0
  - ipython=9.5.0=py312haa95532_0
  - ipython_pygments_lexers=1.1.1=py312haa95532_0
  - ipywidgets=8.1.7=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jinja2=3.1.6=py312haa95532_0
  - joblib=1.5.2=py312haa95532_0
  - jpeg=9f=ha349fce_0
  - json5=0.9.25=py312haa95532_0
  - jsonpickle=4.1.1=pyhe01879c_0
  - jsonschema=4.25.0=py312haa95532_1
  - jsonschema-specifications=2023.7.1=py312haa95532_1
  - jupyter=1.1.1=py312haa95532_0
  - jupyter-lsp=2.2.5=py312haa95532_0
  - jupyter_client=8.6.3=py312haa95532_0
  - jupyter_console=6.6.3=py312haa95532_1
  - jupyter_core=5.8.1=py312haa95532_0
  - jupyter_events=0.12.0=py312haa95532_0
  - jupyter_server=2.16.0=py312haa95532_0
  - jupyter_server_terminals=0.5.3=py312haa95532_0
  - jupyterlab=4.4.7=py312haa95532_0
  - jupyterlab_pygments=0.3.0=py312haa95532_0
  - jupyterlab_server=2.28.0=py312haa95532_0
  - jupyterlab_widgets=3.0.15=py312haa95532_0
  - kiwisolver=1.4.8=py312h5da7b33_0
  - langcodes=3.5.0=py312haa95532_0
  - language-data=1.3.0=py312haa95532_0
  - lcms2=2.16=h62be587_1
  - lerc=4.0.0=h5da7b33_0
  - libabseil=20250127.0=cxx17_h52369b4_0
  - libavif=1.1.1=h827c3e9_0
  - libbrotlicommon=1.0.9=h827c3e9_9
  - libbrotlidec=1.0.9=h827c3e9_9
  - libbrotlienc=1.0.9=h827c3e9_9
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h5bf469e_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.4=hfaec014_0
  - libgrpc=1.71.0=hf4237ab_0
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libopenjpeg=2.5.4=h02ab6af_1
  - libpng=1.6.50=h46444df_0
  - libpq=17.6=h652a1e2_0
  - libprotobuf=5.29.3=h65a231f_1
  - libre2-11=2024.07.02=h5da7b33_0
  - libsodium=1.0.20=h83e8143_0
  - libssh2=1.11.1=h2addb87_0
  - libthrift=0.15.0=ha2884a9_4
  - libtiff=4.7.0=h404307b_0
  - libtorch=2.6.0=cpu_mkl_hcc61593_106
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - marisa-trie=1.3.1=py312h885b0b7_0
  - markdown-it-py=4.0.0=py312haa95532_0
  - markupsafe=3.0.2=py312h827c3e9_0
  - matplotlib=3.10.6=py312haa95532_1
  - matplotlib-base=3.10.6=py312h43afe63_1
  - matplotlib-inline=0.1.7=py312haa95532_0
  - mdurl=0.1.2=py312haa95532_0
  - mistune=3.1.2=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpc=1.3.1=h827c3e9_0
  - mpfr=4.2.1=h56c3642_0
  - mpmath=1.3.0=py312haa95532_0
  - multidict=6.7.0=py312h02ab6af_0
  - multiprocess=0.70.15=py312haa95532_0
  - murmurhash=1.0.12=py312h5da7b33_0
  - mysql-common=9.3.0=hf582a5b_3
  - mysql-libs=9.3.0=hc0ebf12_3
  - narwhals=2.10.2=pyhcf101f3_0
  - nbclient=0.10.2=py312haa95532_0
  - nbconvert=7.16.6=py312haa95532_0
  - nbconvert-core=7.16.6=py312haa95532_0
  - nbconvert-pandoc=7.16.6=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.5=py312haa95532_0
  - notebook-shim=0.2.4=py312haa95532_0
  - numexpr=2.11.0=py312hdb065b2_0
  - numpy=1.26.4=py312hfd52020_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openpyxl=3.1.5=py312h827c3e9_1
  - openssl=3.5.4=h725018a_0
  - opentelemetry-api=1.37.0=py312haa95532_0
  - orc=2.2.0=hf43e1a1_0
  - overrides=7.7.0=py312haa95532_0
  - packaging=25.0=py312haa95532_1
  - pandas=2.3.3=py312h42c1672_1
  - pandoc=3.8=haa95532_0
  - pandocfilters=1.5.1=py312haa95532_0
  - parso=0.8.4=py312haa95532_0
  - pcre2=10.46=h5740b90_0
  - pillow=12.0.0=py312h4212202_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - platformdirs=4.5.0=py312haa95532_0
  - plotly=6.4.0=pyhd8ed1ab_0
  - preshed=3.0.9=py312h5da7b33_0
  - prometheus_client=0.21.1=py312haa95532_0
  - prompt-toolkit=3.0.52=py312haa95532_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py312h827c3e9_0
  - protobuf=5.29.3=py312h5da7b33_0
  - psutil=7.0.0=py312h02ab6af_1
  - pure_eval=0.2.3=py312haa95532_0
  - pyarrow=21.0.0=py312ha5e6156_0
  - pycares=4.10.0=py312he29e43d_0
  - pycparser=2.23=py312haa95532_0
  - pydantic=2.12.3=py312haa95532_1
  - pydantic-core=2.41.4=py312h114bc41_0
  - pydeck=0.8.0=pyhd8ed1ab_0
  - pygments=2.19.2=py312haa95532_0
  - pyparsing=3.2.0=py312haa95532_0
  - pyqt=6.9.1=py312h12ec796_0
  - pyqt6-sip=13.10.2=py312h630b2a1_0
  - pysocks=1.7.1=py312haa95532_1
  - python=3.12.12=h716150d_1
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-json-logger=3.2.1=py312haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py312h827c3e9_0
  - pytorch=2.6.0=cpu_mkl_py312h6e8a95c_106
  - pytz=2025.2=py312haa95532_0
  - pyvis=0.3.2=pyhd8ed1ab_1
  - pywin32=311=py312h885b0b7_0
  - pywinpty=2.0.15=py312h72d21ff_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=27.1.0=py312h7149c55_1
  - qtbase=6.9.2=hd965823_2
  - qtconsole=5.7.0=py312haa95532_0
  - qtdeclarative=6.9.2=h88b4c33_1
  - qtpy=2.4.3=py312haa95532_0
  - qtsvg=6.9.2=h30ace32_1
  - qttools=6.9.2=h7e7b719_1
  - qtwebchannel=6.9.2=heb02b0b_1
  - qtwebsockets=6.9.2=heb02b0b_1
  - re2=2024.07.02=h214f63a_0
  - referencing=0.37.0=py312haa95532_0
  - regex=2025.9.1=py312h02ab6af_0
  - requests=2.32.5=py312haa95532_1
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - rich=13.9.4=py312haa95532_0
  - rpds-py=0.28.0=py312h114bc41_0
  - safetensors=0.6.2=py312h114bc41_0
  - scikit-learn=1.7.2=py312h9296b3f_0
  - scipy=1.12.0=py312hbb039d4_0
  - send2trash=1.8.2=py312haa95532_1
  - setuptools=80.9.0=py312haa95532_0
  - shellingham=1.5.4=py312haa95532_0
  - sip=6.12.0=py312h706e071_0
  - six=1.17.0=py312haa95532_0
  - sleef=3.5.1=h8cc25b3_2
  - smart_open=5.2.1=py312haa95532_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=hcdb6601_0
  - sniffio=1.3.0=py312haa95532_0
  - soupsieve=2.5=py312haa95532_0
  - spacy=3.7.2=py312h7595494_0
  - spacy-legacy=3.0.12=py312haa95532_0
  - spacy-loggers=1.0.4=py312haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - srsly=2.5.1=py312h5da7b33_0
  - stack_data=0.6.3=py312haa95532_0
  - streamlit=1.51.0=pyhd8ed1ab_0
  - sympy=1.14.0=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - tbb-devel=2021.8.0=h59b6b97_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - terminado=0.18.1=py312haa95532_0
  - thinc=8.2.2=py312h82e57e1_0
  - threadpoolctl=3.5.0=py312hfc267ef_0
  - tinycss2=1.4.0=py312haa95532_0
  - tk=8.6.15=hf199647_0
  - tokenizers=0.21.0=py312h482ea96_0
  - toml=0.10.2=pyhd8ed1ab_1
  - tornado=6.5.1=py312h827c3e9_0
  - tqdm=4.67.1=py312hfc267ef_0
  - traitlets=5.14.3=py312haa95532_0
  - transformers=4.51.3=py312haa95532_0
  - typer=0.9.0=py312haa95532_0
  - typing-extensions=4.15.0=py312haa95532_0
  - typing-inspection=0.4.2=py312haa95532_0
  - typing_extensions=4.15.0=py312haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py312haa95532_0
  - utf8proc=2.6.1=h2bbff1b_1
  - vadersentiment=3.3.2=pyhd8ed1ab_1
  - vc=14.42=haa95532_5
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wasabi=1.1.3=py312haa95532_0
  - watchdog=6.0.0=py312haa95532_0
  - wcwidth=0.2.13=py312haa95532_0
  - weasel=0.3.4=py312haa95532_0
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.45.1=py312haa95532_0
  - widgetsnbextension=4.0.14=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_1
  - winloop=0.3.1=py312h913537a_0
  - winpty=0.4.3=4
  - wrapt=1.17.0=py312h827c3e9_0
  - xxhash=0.8.0=h2bbff1b_3
  - xz=5.6.4=h4754444_1
  - yaml=0.2.5=he774522_0
  - yarl=1.22.0=py312h02ab6af_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.21.0=py312haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - en-core-web-sm==3.8.0
      - nltk==3.9.2
      - nrclex==3.0.0
      - seaborn==0.13.2
      - textblob==0.19.0
      - wordcloud==1.9.4
prefix: C:\Users\sanja\anaconda3\envs\nlp_basics
